plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "c:\\Users\\reena\\Downloads\\LearnoHub\\LearnoHub\\frontend\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "c:\\Users\\reena\\Downloads\\LearnoHub\\LearnoHub\\frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]